modLoader="javafml" # mandatory
loaderVersion="[40,)" # Forge for 1.18.2 starts at 40.x
license="MIT"
# Optional: replace with a real link later
# issueTrackerURL="https://github.com/yourname/yourmod/issues"

[[mods]]
modId="ctbackport"
version="1.0.0"
displayName="Creaking Trial Backport"
authors="Natsu91"
accessTransformer = "META-INF/accesstransformer.cfg"
description='''
Backports features introduced in 1.20.x and 1.21.x to 1.18.2 and 1.19.2
'''


[[dependencies.ctbackport]]
modId="forge"
mandatory=true
versionRange="[40,)" # Forge 40.x = 1.18.2
ordering="NONE"
side="BOTH"

[[dependencies.ctbackport]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"

